version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer: 
    image : portainer/portainer-ce

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
        context: .
        dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket_api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
        context: .
        dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount_api:
      image: ${DOCKER_REGISTRY-}discountapi
      build:
          context: .
          dockerfile: Services/Discount/Discount.Api/Dockerfile

volumes:
  mongo_data:
  portainer_data:  
  postgres_data:  
  pgadmin_data:  